# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351d77f9c199ccfa237ad45e5710dcff171afb755ce5c2750bd2b8e3fe5963449fa243f7f5940c868d7bc3c268df6e9e63921308b1dec81b1f6dc4a3c1fa7936

test:
  secret_key_base: 6d46d2d1601adf58d01668932f4811fe2d209beb0f943f77466da6f22f4f60a87922f2450d43b9c099bc17b00fc808c694511d6156c40b16a23c0be7ca29de85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
